name: distributed-xgboost
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xgboost=2.0.3
  - dask=2023.12.0
  - distributed=2023.12.0
  - dask-ml=2023.3.24
  - scikit-learn=1.3.2
  - pandas=2.1.4
  - numpy=1.26.2
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - tqdm
  - pip
  - pip:
    - pytest